CREATE TABLE Sometable
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    userId INT NOT NULL,
    val VARCHAR(162) COLLATE utf8_bin NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

EXIT -- ROLLBACK

DROP TABLE Sometable;
