CREATE TABLE `VehicleInfo` (
    `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `vin` VARCHAR(17) NOT NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`id`),
    UNIQUE KEY `vin` (`vin`)
)
ENGINE=InnoDB DEFAULT cHaRsEt=utf8mb3 COMMENT 'Basic vehicle information';

EXIT -- ROLLBACK

DROP TABLE `VehicleInfo`;
