CREATE TABLE UserPushTokens1 (
    id INT PRIMARY KEY AUTO_INCREMENT,
    userId INT NOT NULL,
    token VARCHAR(162) COLLATE utf8_bin NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
) CHARSET utf8mb4;

CREATE TABLE UserPushTokens2
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    userId INT NOT NULL,
    token VARCHAR(162) COLLATE utf8_bin NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

EXIT -- ROLLBACK

DROP TABLE UserPushTokens1;
DROP TABLE UserPushTokens2;
