CREATE TABLE `VehicleInfo1` (
    `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `vin` VARCHAR(17) NOT NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`id`),
    UNIQUE KEY `vin` (`vin`)
)
ENGINE=InnoDB DEFAULT cHaRsEt=utf8mb4 COMMENT 'Basic vehicle information 1';

CREATE TABLE `VehicleInfo2` (
    `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `vin` VARCHAR(17) NOT NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`id`),
    UNIQUE KEY `vin` (`vin`)
)
ENGINE=InnoDB COMMENT 'Basic vehicle information 2';

EXIT -- ROLLBACK

DROP TABLE `VehicleInfo1`;
DROP TABLE `VehicleInfo2`;
