steps:
  - name: 'gcr.io/connectedcars-staging/cloudbuilder-wrapper.master'
    args: ['--skip-push']
    env:
      - 'NODE_VERSION=10.x'
      - 'REPO_NAME=$REPO_NAME'
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - 'BUILD_ID=$BUILD_ID'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'TAG_NAME=$TAG_NAME'
      - 'COMMIT_SHA=$COMMIT_SHA'
timeout: 3600s
