ALTER TABLE CarVinLicensePlates MODIFY updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

EXIT -- ROLLBACK

ALTER TABLE CarVinLicensePlates MODIFY updatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
