CREATE TABLE UserPushTokens1
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    userId INT NOT NULL,
    token VARCHAR(162) COLLATE utf8_bin NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
) COLLATE utf8mb4_general_ci;

CREATE TABLE UserPushTokens2
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    userId INT NOT NULL,
    token VARCHAR(162) COLLATE utf8_bin NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE UserPushTokens3
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    userId INT NOT NULL,
    token VARCHAR(162) COLLATE utf8_bin NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE UserPushTokens4 (
    id INT PRIMARY KEY AUTO_INCREMENT,
    userId INT NOT NULL,
    token VARCHAR(162) COLLATE utf8_bin NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

EXIT -- ROLLBACK

DROP TABLE UserPushTokens1;
DROP TABLE UserPushTokens2;
DROP TABLE UserPushTokens3;
DROP TABLE UserPushTokens4;
